# Generated by Django 2.2.18 on 2021-11-29 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('secret_key', models.CharField(max_length=12, unique=True, verbose_name='密钥')),
                ('m3', models.IntegerField(default=1.8, verbose_name='质心前部车载设备等效质量')),
                ('m4', models.IntegerField(default=1.5, verbose_name='质心后部车载设备等效质量')),
                ('l3', models.IntegerField(default=100, verbose_name='质心前部车载设备质心至车架质心的距离')),
                ('l4', models.IntegerField(default=100, verbose_name='质心后部车载设备质心至车架质心的距离')),
            ],
            options={
                'verbose_name': '提交车载设备数据表',
                'verbose_name_plural': '提交车载设备数据表',
                'ordering': ['-update_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
