# Generated by Django 2.2.18 on 2021-11-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmitData',
            new_name='EquipmentSetData',
        ),
        migrations.AlterModelOptions(
            name='equipmentsetdata',
            options={'ordering': ['-update_time'], 'verbose_name': '提交车载设备数据表', 'verbose_name_plural': '提交车载设备数据表'},
        ),
    ]
