# Generated by Django 2.2.18 on 2021-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0002_auto_20211129_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsetdata',
            name='amplitude',
            field=models.IntegerField(default=1000, verbose_name='振动激励正弦函数振幅'),
        ),
        migrations.AddField(
            model_name='equipmentsetdata',
            name='frequency',
            field=models.IntegerField(default=400, verbose_name='振动激励正弦函数频率'),
        ),
    ]
