# Generated by Django 2.2.18 on 2021-11-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0003_auto_20211129_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentSetData',
            new_name='SetData',
        ),
    ]
