# Generated by Django 2.2.18 on 2021-12-01 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0004_auto_20211129_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialPara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('m', models.IntegerField(default=1354.5, verbose_name='车身等效质量')),
                ('m1', models.IntegerField(default=80, verbose_name='前轴非悬挂件等效质量')),
                ('m2', models.IntegerField(default=68.5, verbose_name='后轴非悬挂件等效质量')),
                ('j', models.IntegerField(default=64.3, verbose_name='车身绕质心的转动惯量')),
                ('c1', models.IntegerField(default=600, verbose_name='前悬架系统的等效阻尼系数')),
                ('c2', models.IntegerField(default=550, verbose_name='后悬架系统的等效阻尼系数')),
                ('k1', models.IntegerField(default=18000, verbose_name='前悬架系统的等效刚度')),
                ('k2', models.IntegerField(default=16997, verbose_name='后悬架系统的等效刚度')),
                ('k4', models.IntegerField(default=118000, verbose_name='前轮胎的等效刚度')),
                ('k5', models.IntegerField(default=118000, verbose_name='后轮胎的等效刚度')),
                ('l1', models.IntegerField(default=1.11, verbose_name='前轮中心至车架质心的距离')),
                ('l2', models.IntegerField(default=1.3, verbose_name='后轮中心至车架质心的距离')),
                ('length', models.IntegerField(default=2.41, verbose_name='汽车前后轴之间距离')),
            ],
            options={
                'verbose_name': '初始化参数表',
                'verbose_name_plural': '初始化参数表',
                'ordering': ['-update_time'],
            },
        ),
    ]
