# Generated by Django 2.2.18 on 2021-12-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0005_initialpara'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialpara',
            options={'verbose_name': '初始化参数表', 'verbose_name_plural': '初始化参数表'},
        ),
        migrations.RemoveField(
            model_name='initialpara',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='initialpara',
            name='update_time',
        ),
    ]
