# Generated by Django 2.2.18 on 2021-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0006_auto_20211201_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdata',
            name='amplitude',
            field=models.IntegerField(default=24254.147, verbose_name='振动激励正弦函数振幅'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='frequency',
            field=models.IntegerField(default=4000, verbose_name='振动激励正弦函数频率'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='l3',
            field=models.IntegerField(default=0.5, verbose_name='质心前部车载设备质心至车架质心的距离'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='l4',
            field=models.IntegerField(default=0.6, verbose_name='质心后部车载设备质心至车架质心的距离'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='m3',
            field=models.IntegerField(default=250, verbose_name='质心前部车载设备等效质量'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='m4',
            field=models.IntegerField(default=350, verbose_name='质心后部车载设备等效质量'),
        ),
    ]
