# Generated by Django 2.2.18 on 2021-12-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0007_auto_20211201_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialpara',
            name='c1',
            field=models.DecimalField(decimal_places=6, default=600, max_digits=19, verbose_name='前悬架系统的等效阻尼系数'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='c2',
            field=models.DecimalField(decimal_places=6, default=550, max_digits=19, verbose_name='后悬架系统的等效阻尼系数'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='j',
            field=models.DecimalField(decimal_places=6, default=64.3, max_digits=19, verbose_name='车身绕质心的转动惯量'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='k1',
            field=models.DecimalField(decimal_places=6, default=18000, max_digits=19, verbose_name='前悬架系统的等效刚度'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='k2',
            field=models.DecimalField(decimal_places=6, default=16997, max_digits=19, verbose_name='后悬架系统的等效刚度'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='k4',
            field=models.DecimalField(decimal_places=6, default=118000, max_digits=19, verbose_name='前轮胎的等效刚度'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='k5',
            field=models.DecimalField(decimal_places=6, default=118000, max_digits=19, verbose_name='后轮胎的等效刚度'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='l1',
            field=models.DecimalField(decimal_places=6, default=1.11, max_digits=19, verbose_name='前轮中心至车架质心的距离'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='l2',
            field=models.DecimalField(decimal_places=6, default=1.3, max_digits=19, verbose_name='后轮中心至车架质心的距离'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='length',
            field=models.DecimalField(decimal_places=6, default=2.41, max_digits=19, verbose_name='汽车前后轴之间距离'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='m',
            field=models.DecimalField(decimal_places=6, default=1354.5, max_digits=19, verbose_name='车身等效质量'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='m1',
            field=models.DecimalField(decimal_places=6, default=80, max_digits=19, verbose_name='前轴非悬挂件等效质量'),
        ),
        migrations.AlterField(
            model_name='initialpara',
            name='m2',
            field=models.DecimalField(decimal_places=6, default=68.5, max_digits=19, verbose_name='后轴非悬挂件等效质量'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='amplitude',
            field=models.DecimalField(decimal_places=6, default=24254.147, max_digits=19, verbose_name='振动激励正弦函数振幅'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='frequency',
            field=models.DecimalField(decimal_places=6, default=4000, max_digits=19, verbose_name='振动激励正弦函数频率'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='l3',
            field=models.DecimalField(decimal_places=6, default=0.5, max_digits=19, verbose_name='质心前部车载设备质心至车架质心的距离'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='l4',
            field=models.DecimalField(decimal_places=6, default=0.6, max_digits=19, verbose_name='质心后部车载设备质心至车架质心的距离'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='m3',
            field=models.DecimalField(decimal_places=6, default=250, max_digits=19, verbose_name='质心前部车载设备等效质量'),
        ),
        migrations.AlterField(
            model_name='setdata',
            name='m4',
            field=models.DecimalField(decimal_places=6, default=350, max_digits=19, verbose_name='质心后部车载设备等效质量'),
        ),
    ]
