# Generated by Django 2.2.18 on 2021-12-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0008_auto_20211203_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='setdata',
            name='c5',
            field=models.DecimalField(decimal_places=6, default=1375.075, max_digits=19, verbose_name='质心前部车载设备减震器阻尼系数'),
        ),
        migrations.AddField(
            model_name='setdata',
            name='c6',
            field=models.DecimalField(decimal_places=6, default=1925.13125, max_digits=19, verbose_name='质心后部车载设备减震器阻尼系数'),
        ),
        migrations.AddField(
            model_name='setdata',
            name='k7',
            field=models.DecimalField(decimal_places=6, default=68750, max_digits=19, verbose_name='质心前部车载设备减震器刚度'),
        ),
        migrations.AddField(
            model_name='setdata',
            name='k8',
            field=models.DecimalField(decimal_places=6, default=96250, max_digits=19, verbose_name='质心后部车载设备减震器刚度'),
        ),
    ]
