# Generated by Django 2.2.18 on 2021-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibration', '0009_auto_20211209_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='setdata',
            name='absorber_valid',
            field=models.BooleanField(default=False, verbose_name='是否添加减震器'),
        ),
    ]
